In [2]:
import pandas as pd
import numpy as np
import os

file_path = "DataCoSupplyChainDataset.csv"

df = pd.read_csv(file_path, encoding="cp1252")

print("Dataset Shape:", df.shape)
print(df.columns.tolist())
df.head()

Dataset Shape: (180519, 53)
['Type', 'Days for shipping (real)', 'Days for shipment (scheduled)', 'Benefit per order', 'Sales per customer', 'Delivery Status', 'Late_delivery_risk', 'Category Id', 'Category Name', 'Customer City', 'Customer Country', 'Customer Email', 'Customer Fname', 'Customer Id', 'Customer Lname', 'Customer Password', 'Customer Segment', 'Customer State', 'Customer Street', 'Customer Zipcode', 'Department Id', 'Department Name', 'Latitude', 'Longitude', 'Market', 'Order City', 'Order Country', 'Order Customer Id', 'order date (DateOrders)', 'Order Id', 'Order Item Cardprod Id', 'Order Item Discount', 'Order Item Discount Rate', 'Order Item Id', 'Order Item Product Price', 'Order Item Profit Ratio', 'Order Item Quantity', 'Sales', 'Order Item Total', 'Order Profit Per Order', 'Order Region', 'Order State', 'Order Status', 'Order Zipcode', 'Product Card Id', 'Product Category Id', 'Product Description', 'Product Image', 'Product Name', 'Product Price', 'Product Status', 'shipping date (DateOrders)', 'Shipping Mode']

,Type,Days for shipping (real),Days for shipment (scheduled),Benefit per order,Sales per customer,Delivery Status,Late_delivery_risk,Category Id,Category Name,Customer City,...,Order Zipcode,Product Card Id,Product Category Id,Product Description,Product Image,Product Name,Product Price,Product Status,shipping date (DateOrders),Shipping Mode
0,DEBIT,3,4,91.250000,314.640015,Advance shipping,0,73,Sporting Goods,Caguas,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,2/3/2018 22:56,Standard Class
1,TRANSFER,5,4,-249.089996,311.359985,Late delivery,1,73,Sporting Goods,Caguas,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/18/2018 12:27,Standard Class
2,CASH,4,4,-247.779999,309.720001,Shipping on time,0,73,Sporting Goods,San Jose,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/17/2018 12:06,Standard Class
3,DEBIT,3,4,22.860001,304.809998,Advance shipping,0,73,Sporting Goods,Los Angeles,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/16/2018 11:45,Standard Class
4,PAYMENT,2,4,134.210007,298.250000,Advance shipping,0,73,Sporting Goods,Caguas,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/15/2018 11:24,Standard Class

In [3]:
print(df.info())

print(df[[
    'Order Id',
    'order date (DateOrders)',
    'Category Name',
    'Customer Segment',
    'Shipping Mode',
    'Sales',
    'Order Profit Per Order',
    'Late_delivery_risk'
]].head())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 180519 entries, 0 to 180518
Data columns (total 53 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   Type                           180519 non-null  object
 1   Days for shipping (real)       180519 non-null  int64
 2   Days for shipment (scheduled)  180519 non-null  int64
 3   Benefit per order              180519 non-null  float64
 4   Sales per customer             180519 non-null  float64
 5   Delivery Status                180519 non-null  object
 6   Late_delivery_risk             180519 non-null  int64
 7   Category Id                    180519 non-null  int64
 8   Category Name                  180519 non-null  object
 9   Customer City                  180519 non-null  object
 10  Customer Country               180519 non-null  object
 11  Customer Email                 180519 non-null  object
 12  Customer Fname                 180519 non-null  object
 13  Customer Id                    180519 non-null  int64
 14  Customer Lname                 180511 non-null  object
 15  Customer Password              180519 non-null  object
 16  Customer Segment               180519 non-null  object
 17  Customer State                 180519 non-null  object
 18  Customer Street                180519 non-null  object
 19  Customer Zipcode               180516 non-null  float64
 20  Department Id                  180519 non-null  int64
 21  Department Name                180519 non-null  object
 22  Latitude                       180519 non-null  float64
 23  Longitude                      180519 non-null  float64
 24  Market                         180519 non-null  object
 25  Order City                     180519 non-null  object
 26  Order Country                  180519 non-null  object
 27  Order Customer Id              180519 non-null  int64
 28  order date (DateOrders)        180519 non-null  object
 29  Order Id                       180519 non-null  int64
 30  Order Item Cardprod Id         180519 non-null  int64
 31  Order Item Discount            180519 non-null  float64
 32  Order Item Discount Rate       180519 non-null  float64
 33  Order Item Id                  180519 non-null  int64
 34  Order Item Product Price       180519 non-null  float64
 35  Order Item Profit Ratio        180519 non-null  float64
 36  Order Item Quantity            180519 non-null  int64
 37  Sales                          180519 non-null  float64
 38  Order Item Total               180519 non-null  float64
 39  Order Profit Per Order         180519 non-null  float64
 40  Order Region                   180519 non-null  object
 41  Order State                    180519 non-null  object
 42  Order Status                   180519 non-null  object
 43  Order Zipcode                  24840 non-null   float64
 44  Product Card Id                180519 non-null  int64
 45  Product Category Id            180519 non-null  int64
 46  Product Description            0 non-null       float64
 47  Product Image                  180519 non-null  object
 48  Product Name                   180519 non-null  object
 49  Product Price                  180519 non-null  float64
 50  Product Status                 180519 non-null  int64
 51  shipping date (DateOrders)     180519 non-null  object
 52  Shipping Mode                  180519 non-null  object
dtypes: float64(15), int64(14), object(24)
memory usage: 73.0+ MB
None
   Order Id order date (DateOrders)   Category Name Customer Segment  \
0     77202         1/31/2018 22:56  Sporting Goods         Consumer
1     75939         1/13/2018 12:27  Sporting Goods         Consumer
2     75938         1/13/2018 12:06  Sporting Goods         Consumer
3     75937         1/13/2018 11:45  Sporting Goods      Home Office
4     75936         1/13/2018 11:24  Sporting Goods        Corporate

    Shipping Mode   Sales  Order Profit Per Order  Late_delivery_risk
0  Standard Class  327.75               91.250000                   0
1  Standard Class  327.75             -249.089996                   1
2  Standard Class  327.75             -247.779999                   0
3  Standard Class  327.75               22.860001                   0
4  Standard Class  327.75              134.210007                   0

In [4]:
df['order date (DateOrders)'] = pd.to_datetime(
    df['order date (DateOrders)'],
    errors='coerce'
)

df['Weekday'] = df['order date (DateOrders)'].dt.day_name()

weekday_analysis = df.groupby('Weekday').agg(
    Total_Orders=('Order Id', 'nunique'),
    Total_Sales=('Sales', 'sum'),
    Total_Profit=('Order Profit Per Order', 'sum'),
    Late_Delivery_Risk=('Late_delivery_risk', 'mean')
).reset_index()

weekday_analysis['Late_Delivery_Risk'] *= 100

weekday_order = [
    'Monday', 'Tuesday', 'Wednesday', 'Thursday',
    'Friday', 'Saturday', 'Sunday'
]

weekday_analysis['Weekday'] = pd.Categorical(
    weekday_analysis['Weekday'],
    categories=weekday_order,
    ordered=True
)

weekday_analysis = weekday_analysis.sort_values('Weekday')

weekday_analysis

     Weekday  Total_Orders   Total_Sales   Total_Profit  Late_Delivery_Risk
1     Monday          9368  5.280298e+06  612331.430216           55.053130
5    Tuesday          9395  5.195252e+06  544637.390415           54.300991
6  Wednesday          9397  5.088116e+06  544067.980202           54.758276
4   Thursday          9395  5.237198e+06  520938.490699           55.005436
0     Friday          9400  5.306701e+06  564628.251019           55.170685
2   Saturday          9430  5.376950e+06  596359.610799           54.395583
3     Sunday          9367  5.300220e+06  583939.820699           55.114469

In [5]:
category_analysis = df.groupby('Category Name').agg(
    Total_Orders=('Order Id', 'nunique'),
    Total_Sales=('Sales', 'sum'),
    Total_Profit=('Order Profit Per Order', 'sum'),
    Late_Delivery_Risk=('Late_delivery_risk', 'mean')
).reset_index()

category_analysis['Late_Delivery_Risk'] *= 100

category_analysis = category_analysis.sort_values(
    'Total_Sales', ascending=False
)

category_analysis

,Category Name,Total_Orders,Total_Sales,Total_Profit,Late_Delivery_Risk
18,Fishing,15164,6.929654e+06,756220.767190,54.926407
12,Cleats,20386,4.431943e+06,494636.919791,54.971284
9,Camping & Hiking,12299,4.118426e+06,427455.568106,54.534198
10,Cardio Equipment,11355,3.694843e+06,383011.098485,54.496677
47,Women's Apparel,17869,3.147800e+06,350421.029567,54.556691
46,Water Sports,13758,3.113845e+06,325146.960038,54.806950
34,Men's Footwear,18783,2.891758e+06,311902.820214,54.486200
30,Indoor/Outdoor Games,16623,2.888994e+06,318451.430554,54.746606
38,Shop By Sport,10136,1.309522e+06,129813.960315,55.152950
13,Computers,442,6.630000e+05,69656.810171,50.678733
17,Electronics,3061,3.710346e+05,40891.379918,56.083650
8,Cameras,592,2.676077e+05,30289.799946,58.108108
20,Garden,484,2.577687e+05,33443.010106,55.785124
11,Children's Clothing,652,2.328292e+05,27178.099597,53.374233
15,Crafts,484,2.233563e+05,25531.170060,55.991736
21,Girls' Apparel,1191,1.517062e+05,17288.569973,55.287261
48,Women's Clothing,650,1.402830e+05,19102.849930,56.461538
0,Accessories,1753,1.336715e+05,16643.520074,56.966292
40,Sporting Goods,357,1.170068e+05,12518.610119,55.462185
25,Golf Gloves,1064,1.166954e+05,12975.490078,56.261682
36,Music,434,1.131221e+05,14436.319923,57.142857
14,Consumer Electronics,431,1.089913e+05,13223.399926,55.220418
26,Golf Shoes,523,1.079980e+05,12406.070143,55.534351
27,Health and Beauty,362,1.060805e+05,9493.629974,55.801105
31,Kids' Golf Clubs,373,9.879758e+04,9045.839896,53.385417
3,Baseball & Softball,628,9.405715e+04,12762.130067,55.221519
6,Boxing & MMA,421,8.520541e+04,8641.370006,56.264775
16,DVDs,483,7.939554e+04,6655.430088,53.623188
24,Golf Balls,1444,7.709816e+04,8342.670024,54.576271
44,Trade-In,964,6.872178e+04,7915.369985,55.646817
29,Hunting & Shooting,436,5.684842e+04,5979.999945,56.136364
41,Strength Training,111,5.489553e+04,332.310091,57.657658
28,Hockey,609,4.836073e+04,5397.430013,53.583062
35,Men's Golf Clubs,280,4.703580e+04,5517.989977,47.703180
42,Tennis & Racquet,327,4.458509e+04,5747.979996,55.792683
49,Women's Golf Clubs,181,4.454597e+04,5028.639929,53.591160
33,Men's Clothing,208,4.385680e+04,2006.039969,54.326923
37,Pet Supplies,492,4.152480e+04,3589.259959,58.943089
32,Lacrosse,341,3.946479e+04,4364.289984,60.058309
19,Fitness Accessories,307,3.560144e+04,5258.390016,56.957929
22,Golf Apparel,440,3.496975e+04,3496.309983,51.927438
45,Video Games,838,3.331050e+04,2717.519997,54.295943
4,Basketball,64,2.709933e+04,1845.670003,55.223881
39,Soccer,136,2.647705e+04,3901.949953,54.347826
1,As Seen on TV!,68,2.059794e+04,714.429980,57.352941
5,Books,405,1.258740e+04,883.010008,56.543210
2,Baby,207,1.222956e+04,1525.029992,52.657005
23,Golf Bags & Carts,61,1.036939e+04,1810.069992,68.852459
43,Toys,529,6.104660e+03,900.710000,55.009452
7,CDs,271,3.059590e+03,383.850000,52.029520

In [7]:
def analyze_segment(data, column):
    result = data.groupby(column, dropna=False).agg(
        Total_Orders=('Order Id', 'nunique'),
        Total_Sales=('Sales', 'sum'),
        Total_Profit=('Order Profit Per Order', 'sum'),
        Late_Delivery_Risk=('Late_delivery_risk', 'mean')
    ).reset_index()

    result['Late_Delivery_Risk'] *= 100

    return result.sort_values('Total_Sales', ascending=False)


customer_analysis = analyze_segment(df, 'Customer Segment')
shipping_analysis = analyze_segment(df, 'Shipping Mode')
market_analysis = analyze_segment(df, 'Market')

print("Customer Segment Analysis")
display(customer_analysis)

print("Shipping Mode Analysis")
display(shipping_analysis)

print("Market Analysis")
display(market_analysis)

Customer Segment Analysis

,Customer Segment,Total_Orders,Total_Sales,Total_Profit,Late_Delivery_Risk
0,Consumer,34119,1.909579e+07,2.073488e+06,54.808350
1,Corporate,19856,1.116841e+07,1.202575e+06,54.722663
2,Home Office,11777,6.520538e+06,6.908403e+05,55.070440

Shipping Mode Analysis

,Shipping Mode,Total_Orders,Total_Sales,Total_Profit,Late_Delivery_Risk
3,Standard Class,39324,2.202239e+07,2.370454e+06,38.071683
2,Second Class,12778,7.145445e+06,7.503082e+05,76.632781
0,First Class,10079,5.674370e+06,6.431219e+05,95.322499
1,Same Day,3571,1.942529e+06,2.030184e+05,45.743042

Market Analysis

         Market  Total_Orders   Total_Sales  Total_Profit  Late_Delivery_Risk
1        Europe         18561  1.087240e+07  1.169443e+06           55.207753
2         LATAM         17181  1.027761e+07  1.123322e+06           54.355158
3  Pacific Asia         17577  8.273744e+06  8.577534e+05           55.046049
4          USCA          8579  5.066529e+06  5.643138e+05           54.800574
0        Africa          3854  2.294453e+06  2.520712e+05           54.589289

In [8]:
print(df['Delivery Status'].value_counts(dropna=False))

Delivery Status
Late delivery        98977
Advance shipping     41592
Shipping on time     32196
Shipping canceled     7754
Name: count, dtype: int64

In [9]:
df['Is_Late_Delivery'] = (
    df['Delivery Status'].astype(str).str.strip().str.lower()
    == 'late delivery'
)

issue_analysis = df.groupby('Category Name').agg(
    Total_Orders=('Order Id', 'nunique'),
    Late_Delivery_Records=('Is_Late_Delivery', 'sum'),
    Total_Sales=('Sales', 'sum')
).reset_index()

issue_analysis['Late_Delivery_Rate_%'] = (
    issue_analysis['Late_Delivery_Records']
    / issue_analysis['Total_Orders'].replace(0, np.nan)
) * 100

issue_analysis = issue_analysis.sort_values(
    'Late_Delivery_Rate_%', ascending=False
)

issue_analysis

,Category Name,Total_Orders,Late_Delivery_Records,Total_Sales,Late_Delivery_Rate_%
23,Golf Bags & Carts,61,42,1.036939e+04,68.852459
12,Cleats,20386,13496,4.431943e+06,66.202296
34,Men's Footwear,18783,12121,2.891758e+06,64.531757
47,Women's Apparel,17869,11476,3.147800e+06,64.222956
30,Indoor/Outdoor Games,16623,10565,2.888994e+06,63.556518
18,Fishing,15164,9516,6.929654e+06,62.753891
46,Water Sports,13758,8517,3.113845e+06,61.905800
9,Camping & Hiking,12299,7487,4.118426e+06,60.874868
32,Lacrosse,341,206,3.946479e+04,60.410557
10,Cardio Equipment,11355,6805,3.694843e+06,59.929546
38,Shop By Sport,10136,6058,1.309522e+06,59.767167
37,Pet Supplies,492,290,4.152480e+04,58.943089
8,Cameras,592,344,2.676077e+05,58.108108
0,Accessories,1753,1014,1.336715e+05,57.843697
17,Electronics,3061,1770,3.710346e+05,57.824240
4,Basketball,64,37,2.709933e+04,57.812500
41,Strength Training,111,64,5.489553e+04,57.657658
1,As Seen on TV!,68,39,2.059794e+04,57.352941
19,Fitness Accessories,307,176,3.560144e+04,57.328990
36,Music,434,248,1.131221e+05,57.142857
29,Hunting & Shooting,436,247,5.684842e+04,56.651376
25,Golf Gloves,1064,602,1.166954e+05,56.578947
5,Books,405,229,1.258740e+04,56.543210
6,Boxing & MMA,421,238,8.520541e+04,56.532067
48,Women's Clothing,650,367,1.402830e+05,56.461538
44,Trade-In,964,542,6.872178e+04,56.224066
15,Crafts,484,271,2.233563e+05,55.991736
42,Tennis & Racquet,327,183,4.458509e+04,55.963303
27,Health and Beauty,362,202,1.060805e+05,55.801105
20,Garden,484,270,2.577687e+05,55.785124
21,Girls' Apparel,1191,664,1.517062e+05,55.751469
24,Golf Balls,1444,805,7.709816e+04,55.747922
26,Golf Shoes,523,291,1.079980e+05,55.640535
3,Baseball & Softball,628,349,9.405715e+04,55.573248
40,Sporting Goods,357,198,1.170068e+05,55.462185
14,Consumer Electronics,431,238,1.089913e+05,55.220418
39,Soccer,136,75,2.647705e+04,55.147059
43,Toys,529,291,6.104660e+03,55.009452
31,Kids' Golf Clubs,373,205,9.879758e+04,54.959786
33,Men's Clothing,208,113,4.385680e+04,54.326923
45,Video Games,838,455,3.331050e+04,54.295943
28,Hockey,609,329,4.836073e+04,54.022989
16,DVDs,483,259,7.939554e+04,53.623188
49,Women's Golf Clubs,181,97,4.454597e+04,53.591160
11,Children's Clothing,652,348,2.328292e+05,53.374233
2,Baby,207,109,1.222956e+04,52.657005
22,Golf Apparel,440,229,3.496975e+04,52.045455
7,CDs,271,141,3.059590e+03,52.029520
13,Computers,442,224,6.630000e+05,50.678733
35,Men's Golf Clubs,280,135,4.703580e+04,48.214286